language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - |
    pip install -r dev-requirements.txt
script:
  - pytest --vcr-record=none --cov=tenable tests
branches:
  only:
  - master
  - stable
before_deploy:
  - m2r README.md
deploy:
  provider: pypi
  user: stevemcgrath
  password:
    secure: qV8Oku7KmlkxZwbgwYvs7mEH767L0DpHEx7OrMWz9YMAMVJdlFNyEGsAB3sgu8yE7alN2Y2QxIvmImpZqpbN+4dtOLf15/NrT1+jZqjiRkiodouzXFR+oJVlnO5CIgoJ4psWRKXRv3aBcnW0PSt7SAxmGTPUy6zh60HMYO7dGkpla9dkH07hh/7fCmnsrzhfEbqxZP9gBRJgvdSUqS+VSqFvGRBIQbfE+DJEbMqIqezIBVlC3WggEAGJzLpSmuzBOsVCwDRtKjHEb/u7t+n1S/zFacXkEEfBs8r04vtLp1tKVcfwo/u08W+uBecJqDpkWAmRAvih5iSnQaQmL4lWVP+wxl7mDKng1n3Vd5M6+O0tGF01gzqVy7l3DMFCdDpc9fPdzrbnb2Iqby7/W5Bx28v2QkwGeHANYskpgxnmqwEek18J6TppDt1Fe4H9kZslZFb+6bRxzGy2cO+344sJO8NFMirqfSh1wPdn5RdrDeLz/C/JKqu1UoiGiLMwZIKCimka7I4Cd5RC9v2GT1ota4Yuq1b9Q113rqHcZ1yh9f4e6XBimyq/r2RvE9GSI/7tPI0CL2oM+3MhXtAMuQCWLco9G9WrUx+Bkfy2YbU61JptwQCO+pZgkKl7wF/x4djD9k0JomYGT2H76Mz/AaWQd8u42oLwWXLGrxIx1hAu4p4=
  skip_existing: true
  on:
    tags: true